POST http://localhost:8688/api/notes 
Content-Type : application/json

{
    "content" : "Big",
    "important" : "true"
}

###

GET http://localhost:8688/api/notes

###

POST http://localhost:8688/api/notes 
Content-Type : application/json

{
    "content" : "King",
    "important" : "true"
}

###
POST http://localhost:8688/api/notes 
Content-Type : application/json 

{
    "content" : "Elanga",
    "important" : "true"
}