POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Testing my new setup",
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Check whether it functioning",
    "imporntant": true
}